#############################
### Project configuration ###
#############################

# Indicate working directory and metadata (sample) table
# data is expected in the data/ folder relative to the working directory
# need to write an "expected inputs/structure" doc for data/

workdir: "/global/scratch/users/stacy-l/spermSV"
sample_table: "/global/scratch/users/stacy-l/spermSV/config/snakemake/samples.tsv"

##########################
### Path configuration ###
##########################

# Specify paths to scripts, packages, and other tools not managed by conda
# Working on helper functions for managing environmental $PATH as necessary.

paths:
  HiFiAdapterFilt: 
    repo: "/global/scratch/users/stacy-l/spermSV/code/HiFiAdapterFilt"
    db: "/global/scratch/users/stacy-l/spermSV/code/HiFiAdapterFilt/DB"
  # trgt:
  #   repo: "/global/scratch/users/stacy-l/spermSV/code/trgt"
  #   catalog: "/global/scratch/users/stacy-l/spermSV/code/trgt/repeats/repeat_catalog.hg38.bed"
  
###############################
### Analysis config options ###
###############################

# Indicate reference genome + annotation files (.bed, .gff, etc)
# The alias will be used for organizing mapping outputs:
# for example, output/mapping/CHM13 or output/mapping/hg38_no_alts

reference:
  fasta: "/global/scratch/users/stacy-l/references/T2T_CHM13/hs1.fa"
  alias: "CHM13"
  annotations:
    repeats: "/global/scratch/users/stacy-l/references/T2T_CHM13/T2T_CHM13_simpleRepeat.bed"
    segdups: "/global/scratch/users/stacy-l/references/T2T_CHM13/T2T_CHM13_sedefSegDups.bed"
    censat: "/global/scratch/users/stacy-l/references/T2T_CHM13/T2T_CHM13_censat.bed"

minimap2:
  readgroup: "@RG\\tID:{lane}\\tSM:{specimen}\\tPU:{smrtcell}\\tPL:PACBIO"

winnowmap:
  readgroup: "'@RG\\tID:{lane}\\tSM:{specimen}\\tPU:{smrtcell}\\tPL:PACBIO'"

meryl:
  k: 15
  distinct: 0.9998

samtools:
  minQ: 10
  readgroup: "'@RG\\tID:{specimen}\\tSM:{specimen}\\tPL:PACBIO'"

sniffles:
  minsupport: 1
  mapq: 20
  mosaic-af-min: 0
  mosaic-qc-strand: False

repeatmasker:
  species: "human"
  engine: "rmblast"

pepper_etc:
  mapQ: 10

singularity:
  mount_dir: "/global/scratch/users/stacy-l"