#############################
### Project configuration ###
#############################

# Indicate working directory and metadata (sample) table
# data is expected in the data/ folder relative to the working directory
# need to write an "expected inputs/structure" doc for data/

workdir: "/global/scratch/users/stacy-l/spermSV"
sample_table: "/global/scratch/users/stacy-l/spermSV/config/snakemake/samples.tsv"

##########################
### Path configuration ###
##########################

# Specify paths to scripts, packages, and other tools not managed by conda
# Working on helper functions for managing environmental $PATH as necessary.

paths:
  HiFiAdapterFilt: 
    repo: "/global/scratch/users/stacy-l/spermSV/code/HiFiAdapterFilt"
    db: "/global/scratch/users/stacy-l/spermSV/code/HiFiAdapterFilt/DB"
  trgt:
    repeat_catalog: "/global/scratch/users/stacy-l/spermSV/code/trgt/repeats/repeat_catalog.hg38.bed"
    pathogenic: "/global/scratch/users/stacy-l/spermSV/code/trgt/repeats/pathogenic_repeats.hg38.bed"
  sim-it:
    repo: "/global/scratch/users/stacy-l/spermSV/code/Sim-it"
  
###############################
### Analysis config options ###
###############################

# Indicate reference genome + annotation files (.bed, .gff, etc)
# The alias will be used for organizing mapping outputs:
# for example, output/alignment/CHM13 or output/alignment/hg38_no_alts

reference:
  fasta: "/global/scratch/users/stacy-l/references/hg38_HGSVC/hg38.no_alt.fa.gz"
  alias: "hg38"
  annotations:
    repeats: "/global/scratch/users/stacy-l/references/hg38_HGSVC/GRCh38_simpleRepeat.bed"
    segdups: "/global/scratch/users/stacy-l/references/hg38_HGSVC/GRCh38_genomicSuperDups.bed"
    censat: "/global/scratch/users/stacy-l/references/hg38_HGSVC/GRCh38_centromeres.bed"
    cpg: "/global/scratch/users/stacy-l/references/hg38_HGSVC/GRCh38_cpgIslandExt.bed"
    plof: "/global/scratch/users/stacy-l/references/hg38_HGSVC/GRCh38_gnomAD_geneLoF.bed"
    microsat: "/global/scratch/users/stacy-l/references/hg38_HGSVC/GRCh38_microsat.bed"
    repeatmasker: "/global/scratch/users/stacy-l/references/hg38_HGSVC/GRCh38_repeatmasker.bed"
    refseq: "/global/scratch/users/stacy-l/references/hg38_HGSVC/hg38.ncbiRefSeq.gtf.gz"
    gencode: "/global/scratch/users/stacy-l/references/hg38_HGSVC/gencode.v44.basic.annotation.gff3.gz"
  benchmarks:
    svtier1: 
      all: "/global/scratch/users/stacy-l/spermSV/benchmarks/HG002/liftovervcf/hg38/HG002_hg38_SVs_Tier1_v0.6_withChr.vcf.gz"
    cmrg:
      all: "/global/scratch/users/stacy-l/spermSV/benchmarks/HG002/liftover/HG002_GRCh38_CMRG_SV_v1.00.vcf.gz"

minimap2:
  readgroup: "@RG\\tID:{specimen}\\tSM:{specimen}\\tPL:PACBIO"

winnowmap:
  readgroup: "'@RG\\tID:{specimen}\\tSM:{specimen}\\tPL:PACBIO'"

duplomap:
  db: "/global/scratch/users/stacy-l/spermSV/config/packages/duplomap/hg38"

meryl:
  k: 15
  distinct: 0.9998

samtools:
  minQ: 10
  readgroup: "'@RG\\tID:{specimen}\\tSM:{specimen}\\tPL:PACBIO'"

sniffles:
  minsupport: 1
  mapq: 20
  mosaic-af-min: 0
  mosaic-af-max: 0.2
  mosaic-qc-strand: False


# The current HG002 coverage with hg38 + winnowmap (below, "refcoverage") is ~37X.
# Obviously, the coverage number can only be filled in here to parameterize simulations *after* mapping is complete.
# It's not a GREAT solution, but it's okay.
# Once refcoverage is established, fractional subsampling can be automated via the simulations.smk code.
simulations:
  spike:
    control: 
      sample: 'HG002'
      coverage: 37
    svlen: 10000
  survivor:
    refgenome: '/global/scratch/users/stacy-l/references/hg38_HGSVC/hg38.no_alt.fa'
    error_profile:
      minreadlen: 10000
      fraction: 0.15
    snp_fraction: 0
    coverage: 20
  simit:
    reference: '/global/scratch/users/stacy-l/references/hg38_ucsc/hg38.analysisSet.chroms/chr1.fa'

repeatmasker:
  species: "human"
  engine: "rmblast"

pepper_etc:
  mapQ: 10

singularity:
  mount_dir: "/global/scratch/users/stacy-l"